nginx_install_method: "source" # choices ("package", "source")
nginx_version: 1.6.0

nginx_group: "nginxxyz"
nginx_user: "nginxxyz"
nginx_user_password: None

nginx_dir: /etc/nginx
nginx_www_dir: /var/www
nginx_log_dir: /var/log/nginx
nginx_home_dir: "{{ nginx_www_dir }}"

# site inventory
## default site
default_site: True # choices (True, False)
nginx_sites: []
# nginx_site examples:
# - name: abhinav
#   path: /home/users/abhinavmehta/sites/abhinav
# - name: mehta
#   path: /home/users/abhinavmehta/sites/mehta

# nginx install from source settings
nginx_source_install_prefix: /usr/local/etc
nginx_source_install_conf_path: /etc/nginx/nginx.conf

# nginx.conf
nginx_worker_processes: 4
nginx_daemon_disable: no
nginx_worker_rlimit_nofile: null
nginx_error_log_options: null
nginx_worker_connections: 1024
nginx_multi_accept: 'on'
nginx_event: null
nginx_charset: null
nginx_disable_access_log: no
nginx_access_log_options: null
nginx_server_tokens: null
nginx_sendfile: 'on'
nginx_keepalive: "on"
nginx_keepalive_timeout: "30"
nginx_client_body_timeout: "10"
nginx_client_header_timeout: "10"
nginx_send_timeout: "10"
nginx_buffers: "on"
nginx_client_body_buffer_size: "8k"
nginx_client_header_buffer_size: "1k"
nginx_client_max_body_size: "2m"
nginx_large_client_header_buffers: "2 1k"
nginx_server_names_hash_bucket_size: 64
nginx_types_hash_max_size: 2048
nginx_types_hash_bucket_size: 64
nginx_proxy_read_timeout: null
nginx_enable_rate_limiting: no
nginx_rate_limiting_zone_name: "default"
nginx_rate_limiting_backoff: "10m"
nginx_rate_limit: "1r/s"

# gzip_module
nginx_gzip: 'on'
nginx_gzip_http_version: 1.1
nginx_gzip_comp_level: 2
nginx_gzip_proxied: expired no-cache no-store private auth
nginx_gzip_vary: 'on'
nginx_gzip_buffers: null
nginx_gzip_min_length: 10240
nginx_gzip_types:
  - text/plain
  - text/css
  - text/xml
  - text/csv
  - text/javascript
  - application/x-javascript
  - application/xml
  - application/xml+rss
  - application/javascript
  - application/postscript
  - application/pdf
  - application/ecmascript
  - application/json
  - image/svg+xml
nginx_gzip_disable: "MSIE [1-6]\\."

# nginx modules support: EXCLUDED
nginx_source_modules_excluded:
  - mail_pop3_module ## pop3 settings
  - mail_imap_module ## imap settings
  - mail_smtp_module ## smtp settings
  - http_empty_gif_module ## serve a 1x1 image from memory
  - http_fastcgi_module ## module allows passing requests to a FastCGI server
  # - http_geo_module ## creates variables with values depending on the client IP address
  - http_memcached_module ## used to obtain responses from a memcached server
  - http_proxy_module ## allows passing requests to another server
  - http_referer_module ## module is used to block access to a site for requests with invalid values in the “Referer” header field
  # - http_rewrite_module ## used to change request URI using regular expressions, return redirects, and conditionally select configurations
  - http_scgi_module ## allows Nginx to interact with SCGI processes and control what parameters are passed to the process
  - http_split_clients_module ## creates variables suitable for A/B testing, also known as split testing.
  - http_upstream_ip_hash_module ## used to define groups of servers that can be referenced by the proxy_pass, fastcgi_pass, and memcached_pass directives
  - http_userid_module ## sets cookies suitable for client identification
  - http_uwsgi_module ## allows Nginx to interact with uWSGI processes and control what parameters are passed to the process

# nginx modules support: INCLUDED
nginx_source_modules_included:
  ## *** STANDARD MODULES ***
  http_stub_status_module: "--with-http_stub_status_module" ## provides the ability to get some status from nginx
  http_ssl_module: "--with-http_ssl_module" ## HTTP-SSL support
  http_gzip_static_module: "--with-http_gzip_static_module" ## allows sending precompressed files with the “.gz” filename extension instead of regular files
  http_auth_request_module: "--with-http_auth_request_module" ## implements client authorization based on the result of a subrequest
  google_perftools_module: "--with-google_perftools_module" ## google Performance Tools support
  ipv6_module: "--with-ipv6"
  http_real_ip_module: "--with-http_realip_module" ## used to change the client address to the one sent in the specified header field
  http_spdy_module: "--with-http_spdy_module" ## SPDY protocol support
  http_perl_module: "--with-http_perl_module" ## used to implement location and variable handlers in Perl and insert Perl calls into SSI.
  http_mp4_module: "--with-http_mp4_module" ## enables mp4 streaming with seeking ability
  debug: "--with-debug" ## CAUTIOUS: will produce high number of logs
  ## ***  NON-STANDARD MODULES ***
  # upload_progress_module: "--add-module=/tmp/nginx_upload_progress" ## to track upload-progress
  headers_more_module: "--add-module=/tmp/nginx_headers_more" ## set and clear input and output headers...more than "add"
  http_echo_module: "--add-module=/tmp/nginx_echo" ## brings "echo", "sleep", "time", "exec" and more shell-style goodies to Nginx config file
  # naxsi_module: "--add-module=/tmp/nginx_naxsi" ## NAXSI means Nginx Anti Xss & Sql Injection




# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
## MODULEWISE CONFIGURATION: STANDARD MODULES
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# http_stub_status_module configuration
nginx_remote_ip_var: "remote_addr"
nginx_authorized_ips:
  - "127.0.0.1/32"

# http_gzip_static_module configuration
nginx_gzip_static: "on" # choices ("on", "off")

# http_auth_request_module configuration
nginx_auth_request_release: "662785733552"
nginx_auth_request_url: "http://mdounin.ru/hg/ngx_http_auth_request_module/archive/{{ nginx_auth_request_release }}.tar.gz"

# http_realip_module configuration
nginx_realip_header: "X-Forwarded-For"
nginx_realip_addresses: ["127.0.0.1"]
nginx_realip_real_ip_recursive: "off"


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
## MODULEWISE CONFIGURATION: NON-STANDARD MODULES
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# upload_progress_module configuration
nginx_upload_progress_version: "0.9.0"
nginx_upload_progress_javascript_output: yes
nginx_upload_progress_zone_name: "proxied"
nginx_upload_progress_zone_size: "1m"
nginx_upload_progress_url: "https://github.com/masterzen/nginx-upload-progress-module/archive/v{{ nginx_upload_progress_version }}.tar.gz"

# headers_more_module configuration
nginx_headers_more_version: "0.25"
nginx_headers_more_url: "https://github.com/agentzh/headers-more-nginx-module/archive/v{{ nginx_headers_more_version }}.tar.gz"

# http_echo_module configuration
nginx_echo_version: "0.53"
nginx_echo_url: "https://github.com/agentzh/echo-nginx-module/archive/v{{nginx_echo_version}}.tar.gz"

# naxsi_module configuration
nginx_naxsi_version: "0.53"
nginx_naxsi_url: "https://github.com/nbs-system/naxsi/archive/{{nginx_naxsi_version}}.tar.gz"




# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
## MAKE YOUR LIFE SIMPLE, AVOID CHANGING FOLLOWING VARS
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
nginx_source_configure_flags: "{{nginx_source_default_configure_flags}}{% for key, value in nginx_source_modules_included.items() %} {{value}}{% endfor %}{% for item in nginx_source_modules_excluded %} --without-{{item}}{% endfor %}"

# source
nginx_source_url: "http://nginx.org/download/nginx-{{nginx_version}}.tar.gz"
nginx_source_prefix: "/usr/local/nginx/nginx-{{nginx_version}}"
nginx_source_conf_path: "{{nginx_dir}}/nginx.conf"
nginx_source_sbin_path: "{{nginx_source_prefix}}/sbin/nginx"
nginx_source_default_configure_flags: "--prefix={{nginx_source_prefix}} --conf-path={{nginx_source_conf_path}} --sbin-path={{nginx_source_sbin_path}}"

nginx_pid: "/var/run/nginx.pid"

nginx_uid: 47  ## 33 TODO: restore commented value
nginx_gid: 47  ## 33 TODO: restore commented value
